import 'package:course_online/dummy/dummy_popular_mentors.dart';
import 'package:course_online/models/course.model.dart';

List<Course> dummyCourses = [
  Course(
    id: '1',
    name: 'Belajar Flutter dari Nol',
    instructor: dummyPopularMentors[6],
    progress: 0.4,
    rating: 4.2,
    image: "assets/images/fluuter.png",
  ),
  Course(
    id: '2',
    name: 'Mastering React JS',
    instructor: dummyPopularMentors[0],
    progress: 0.7,
    rating: 4.9,
    image: "assets/images/react-course.png",
  ),
  Course(
    id: '3',
    name: 'UI/UX Design Fundamentals',
    instructor: dummyPopularMentors[1],
    progress: 1.0,
    rating: 4.5,
    image: "assets/images/course-uiux.jpg",
  ),
];

List<Course> savedCourses = [
  Course(
    id: "1",
    name: "Flutter Development For Beginner Complete 2025",
    instructor: dummyPopularMentors[6],
    price: 200000,
    rating: 4.5,
    countReviews: 200,
    image: "assets/images/flutter-course2.jpeg",
  ),
  Course(
    id: "4",
    name: "Cybersecurity",
    instructor: dummyPopularMentors[3],
    price: 220000,
    rating: 4.4,
    countReviews: 180,
    image: "assets/images/course-cyber.jpg",
  ),
  Course(
    id: "5",
    name: "Machine Learning",
    instructor: dummyPopularMentors[4],
    price: 350000,
    rating: 4.8,
    countReviews: 600,
    image: "assets/images/course-machine.jpeg",
  ),
];

List<Course> dummyPopularCourses = [
  Course(
    id: "1",
    name: "Flutter Development For Beginner Complete 2025",
    instructor: dummyPopularMentors[6],
    price: 200000,
    rating: 4.5,
    countReviews: 200,
    image: "assets/images/flutter-course2.jpeg",
  ),
  Course(
    id: "2",
    name: "UI/UX Design",
    instructor: dummyPopularMentors[1],
    price: 250000,
    rating: 4.3,
    countReviews: 150,
    image: "assets/images/course-uiux.jpg",
  ),
  Course(
    id: "3",
    name: "Data Science",
    instructor: dummyPopularMentors[2],
    price: 300000,
    rating: 4.7,
    countReviews: 400,
    image: "assets/images/course-data.png",
  ),
  Course(
    id: "4",
    name: "Cybersecurity",
    instructor: dummyPopularMentors[3],
    price: 220000,
    rating: 4.4,
    countReviews: 180,
    image: "assets/images/course-cyber.jpg",
  ),
  Course(
    id: "5",
    name: "Machine Learning",
    instructor: dummyPopularMentors[4],
    price: 350000,
    rating: 4.8,
    countReviews: 600,
    image: "assets/images/course-machine.jpeg",
  ),
  Course(
    id: "6",
    name: "Digital Marketing",
    instructor: dummyPopularMentors[5],
    price: 150000,
    rating: 4.2,
    countReviews: 120,
    image: "assets/images/course-digital.png",
  ),
];

List<Course> dummyBestCourses = [
  Course(
    id: "1",
    name: "UI/UX Design",
    instructor: dummyPopularMentors[1],
    price: 250000,
    rating: 4.3,
    countReviews: 150,
    image: "assets/images/course-uiux.jpg",
  ),
  Course(
    id: "2",
    name: "Data Science",
    instructor: dummyPopularMentors[2],
    price: 300000,
    rating: 4.7,
    countReviews: 400,
    image: "assets/images/course-data.png",
  ),
  Course(
    id: "3",
    name: "Flutter Development For Beginner Complete 2025",
    instructor: dummyPopularMentors[6],
    price: 200000,
    rating: 4.5,
    countReviews: 200,
    image: "assets/images/flutter-course2.jpeg",
  ),
  Course(
    id: "4",
    name: "Cybersecurity",
    instructor: dummyPopularMentors[3],
    price: 220000,
    rating: 4.4,
    countReviews: 180,
    image: "assets/images/course-cyber.jpg",
  ),
  Course(
    id: "5",
    name: "Digital Marketing",
    instructor: dummyPopularMentors[5],
    price: 150000,
    rating: 4.2,
    countReviews: 120,
    image: "assets/images/course-digital.png",
  ),
  Course(
    id: "6",
    name: "Machine Learning",
    instructor: dummyPopularMentors[4],
    price: 350000,
    rating: 4.8,
    countReviews: 600,
    image: "assets/images/course-machine.jpeg",
  ),
];
